name: E2E Testing

on:
  deployment_status:
    branches-ignore:
      - main

jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          config: baseUrl=${{ github.event.deployment_status.target_url }}
