name: Update existing data to match new schema

on:
  push:
    branches:
      - "feature/admin-features"

env:
  DATABASE_URL: ${{ vars.DATABASE_URL }}

jobs:
  migrate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm ci

      - run: npm run migration:dev

      - name: Remove migration files
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Remove migration files"
